from typing import Optional, List
from fastapi import APIRouter, Query
from pydantic import BaseModel

router = APIRouter()


class HOFPlayerItem(BaseModel):
    player_id: int
    player_name: str
    status: str  # "inducted" | "active_lock" | "active_high" | "active_contender" | "active_rising"
    induction_year: Optional[int] = None
    hof_probability: float  # 0.0 - 1.0 (e.g. 1.0 = 100%)
    primary_archetype: str
    career_span: str
    team_abbreviation: str
    headshot_url: str
    nba_championships: int
    mvp_count: int
    finals_mvp_count: int
    all_star_count: int
    all_nba_count: int
    dpoy_count: int = 0
    olympic_medals: List[str] = []
    fiba_accolades: List[str] = []
    ncaa_accolades: List[str] = []
    career_ppg: float
    career_rpg: float
    career_apg: float
    peak_per: float
    peak_bpm: float
    tactical_summary: str
    tactical_summary_en: str


HOF_DATABASE: List[HOFPlayerItem] = [
    # --- CONSAGRADOS EN EL HALL OF FAME (ENSHRINED LEGENDS) ---
    HOFPlayerItem(
        player_id=893,
        player_name="Michael Jordan",
        status="inducted",
        induction_year=2009,
        hof_probability=1.0,
        primary_archetype="Primary Ball Handler & Creator",
        career_span="1984 - 2003",
        team_abbreviation="CHI",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/893.png",
        nba_championships=6,
        mvp_count=5,
        finals_mvp_count=6,
        all_star_count=14,
        all_nba_count=11,
        dpoy_count=1,
        olympic_medals=["🥇 Oro Olímpico (1984)", "🥇 Oro Olímpico Dream Team (1992)"],
        fiba_accolades=["🏆 Torneo de las Américas Oro (1992)"],
        ncaa_accolades=["🏆 Campeón Nacional NCAA (1982 UNC)", "🌟 Naismith College Player of the Year (1984)"],
        career_ppg=30.1,
        career_rpg=6.2,
        career_apg=5.3,
        peak_per=31.7,
        peak_bpm=12.6,
        tactical_summary="Máximo anotador por partido en la historia. Dominio bidireccional insuperable, 10 títulos de anotación y récord invicto en Finales (6-0).",
        tactical_summary_en="Highest all-time scoring average in NBA history. Unmatched two-way dominance, 10 scoring titles, and undefeated in NBA Finals (6-0).",
    ),
    HOFPlayerItem(
        player_id=977,
        player_name="Kobe Bryant",
        status="inducted",
        induction_year=2020,
        hof_probability=1.0,
        primary_archetype="Primary Ball Handler & Creator",
        career_span="1996 - 2016",
        team_abbreviation="LAL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/977.png",
        nba_championships=5,
        mvp_count=1,
        finals_mvp_count=2,
        all_star_count=18,
        all_nba_count=15,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico Redeem Team (2008)", "🥇 Oro Olímpico (2012)"],
        fiba_accolades=["🏆 FIBA AmeriCup Oro (2007)"],
        ncaa_accolades=[],
        career_ppg=25.0,
        career_rpg=5.2,
        career_apg=4.7,
        peak_per=28.0,
        peak_bpm=6.5,
        tactical_summary="Uno de los anotadores y competidores más implacables del básquetbol mundial. 18 All-Star, 5 anillos y líder del Redeem Team de USA 2008.",
        tactical_summary_en="One of the most relentless scorers and competitors in basketball history. 18x All-Star, 5x champion, and iconic leader of the 2008 USA Redeem Team.",
    ),
    HOFPlayerItem(
        player_id=406,
        player_name="Shaquille O'Neal",
        status="inducted",
        induction_year=2016,
        hof_probability=1.0,
        primary_archetype="Unicorn & Hub Center",
        career_span="1992 - 2011",
        team_abbreviation="LAL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/406.png",
        nba_championships=4,
        mvp_count=1,
        finals_mvp_count=3,
        all_star_count=15,
        all_nba_count=14,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico (1996)"],
        fiba_accolades=["🏆 Campeonato Mundial FIBA Oro & MVP (1994)"],
        ncaa_accolades=["🌟 2x Consenso All-American (LSU)"],
        career_ppg=23.7,
        career_rpg=10.9,
        career_apg=2.5,
        peak_per=30.6,
        peak_bpm=9.3,
        tactical_summary="La fuerza física y presencia en la pintura más imparable de la era moderna. 3 MVP de Finales consecutivos con los Lakers.",
        tactical_summary_en="The most dominant physical presence in modern NBA history. 3 consecutive Finals MVPs during the historic Lakers three-peat.",
    ),
    HOFPlayerItem(
        player_id=1495,
        player_name="Tim Duncan",
        status="inducted",
        induction_year=2020,
        hof_probability=1.0,
        primary_archetype="Rim Protector & Rolling Big",
        career_span="1997 - 2016",
        team_abbreviation="SAS",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/1495.png",
        nba_championships=5,
        mvp_count=2,
        finals_mvp_count=3,
        all_star_count=15,
        all_nba_count=15,
        dpoy_count=0,
        olympic_medals=["🥉 Bronce Olímpico (2004)"],
        fiba_accolades=["🏆 2x FIBA AmeriCup Oro (1999, 2003)"],
        ncaa_accolades=["🌟 Naismith College Player of the Year (1997 Wake Forest)"],
        career_ppg=19.0,
        career_rpg=10.8,
        career_apg=3.0,
        peak_per=27.1,
        peak_bpm=7.6,
        tactical_summary="El mejor ala-pívot de la historia. 'The Big Fundamental' lideró la dinastía de San Antonio Spurs durante casi dos décadas con excelencia táctica.",
        tactical_summary_en="The greatest power forward in NBA history. 'The Big Fundamental' anchored the San Antonio Spurs dynasty for two decades with unmatched tactical discipline.",
    ),
    HOFPlayerItem(
        player_id=1717,
        player_name="Dirk Nowitzki",
        status="inducted",
        induction_year=2023,
        hof_probability=1.0,
        primary_archetype="Unicorn & Hub Center",
        career_span="1998 - 2019",
        team_abbreviation="DAL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/1717.png",
        nba_championships=1,
        mvp_count=1,
        finals_mvp_count=1,
        all_star_count=14,
        all_nba_count=12,
        dpoy_count=0,
        olympic_medals=[],
        fiba_accolades=["🥉 Mundial FIBA Bronce & MVP (2002 Alemania)", "🥈 EuroBasket Plata & MVP (2005)"],
        ncaa_accolades=[],
        career_ppg=20.7,
        career_rpg=7.5,
        career_apg=2.4,
        peak_per=28.1,
        peak_bpm=6.7,
        tactical_summary="Pionero que revolucionó la posición de pívot tirador con su icónico 'one-legged fadeaway'. Más de 31.500 puntos y título épico en 2011.",
        tactical_summary_en="Pioneer who revolutionized the stretch big position with his iconic one-legged fadeaway. 31,500+ career points and legendary 2011 title run.",
    ),
    HOFPlayerItem(
        player_id=2200,
        player_name="Pau Gasol",
        status="inducted",
        induction_year=2023,
        hof_probability=1.0,
        primary_archetype="Unicorn & Hub Center",
        career_span="2001 - 2019",
        team_abbreviation="LAL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/2200.png",
        nba_championships=2,
        mvp_count=0,
        finals_mvp_count=0,
        all_star_count=6,
        all_nba_count=4,
        dpoy_count=0,
        olympic_medals=["🥈 Plata Olímpica (2008)", "🥈 Plata Olímpica (2012)", "🥉 Bronce Olímpico (2016)"],
        fiba_accolades=["🏆 Campeón del Mundo FIBA & MVP (2006 España)", "🏆 3x Campeón EuroBasket"],
        ncaa_accolades=[],
        career_ppg=17.0,
        career_rpg=9.2,
        career_apg=3.2,
        peak_per=24.1,
        peak_bpm=5.0,
        tactical_summary="Ícono global de la generación de oro española y pieza clave del back-to-back de Lakers (2009-2010). Carrera internacionallegendaria con 3 medallas olímpicas.",
        tactical_summary_en="Global icon of Spain's Golden Generation and centerpiece of the Lakers' back-to-back championships (2009-2010). Triple Olympic medalist.",
    ),
    HOFPlayerItem(
        player_id=1938,
        player_name="Manu Ginóbili",
        status="inducted",
        induction_year=2022,
        hof_probability=1.0,
        primary_archetype="Versatile Wing / Playmaking Forward",
        career_span="2002 - 2018",
        team_abbreviation="SAS",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/1938.png",
        nba_championships=4,
        mvp_count=0,
        finals_mvp_count=0,
        all_star_count=2,
        all_nba_count=2,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico Histórico Atenas (2004 Argentina)", "🥉 Bronce Olímpico (2008)"],
        fiba_accolades=["🥈 Subcampeón Mundial FIBA (2002)", "🏆 Campeón EuroLeague & Finals MVP (2001 Virtus)"],
        ncaa_accolades=[],
        career_ppg=13.3,
        career_rpg=3.5,
        career_apg=3.8,
        peak_per=24.3,
        peak_bpm=6.5,
        tactical_summary="Uno de los competidores más condecorados de la historia del básquetbol mundial. Oro olímpico liderando a la 'Generación Dorada' argentina, EuroLeague MVP y 4 anillos NBA.",
        tactical_summary_en="One of the most decorated winners in world basketball history. Olympic Gold leading Argentina's Golden Generation, EuroLeague Champion & MVP, and 4x NBA champion.",
    ),
    HOFPlayerItem(
        player_id=2548,
        player_name="Dwyane Wade",
        status="inducted",
        induction_year=2023,
        hof_probability=1.0,
        primary_archetype="Primary Ball Handler & Creator",
        career_span="2003 - 2019",
        team_abbreviation="MIA",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/2548.png",
        nba_championships=3,
        mvp_count=0,
        finals_mvp_count=1,
        all_star_count=13,
        all_nba_count=8,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico (2008)", "🥉 Bronce Olímpico (2004)"],
        fiba_accolades=["🥉 Mundial FIBA Bronce (2006)"],
        ncaa_accolades=["🌟 Final Four NCAA (2003 Marquette)"],
        career_ppg=22.0,
        career_rpg=4.7,
        career_apg=5.4,
        peak_per=30.4,
        peak_bpm=10.7,
        tactical_summary="'Flash', uno de los mejores escoltas de la historia. Actuación mítica en las Finales de 2006 con Miami Heat y líder anotador de los Juegos Olímpicos de 2008.",
        tactical_summary_en="'Flash', one of the greatest shooting guards in NBA history. Legendary 2006 Finals MVP performance and leading scorer of the 2008 USA Olympic team.",
    ),

    # --- CANDIDATOS ACTIVOS Y FUTUROS HALL OF FAMERS (ACTIVE CONTENDERS) ---
    HOFPlayerItem(
        player_id=2544,
        player_name="LeBron James",
        status="active_lock",
        induction_year=None,
        hof_probability=1.0,
        primary_archetype="Versatile Wing / Playmaking Forward",
        career_span="2003 - Presente",
        team_abbreviation="LAL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png",
        nba_championships=4,
        mvp_count=4,
        finals_mvp_count=4,
        all_star_count=20,
        all_nba_count=20,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico (2008)", "🥇 Oro Olímpico (2012)", "🥇 Oro Olímpico & MVP (2024)", "🥉 (2004)"],
        fiba_accolades=["🥉 Mundial FIBA Bronce (2006)", "🏆 FIBA AmeriCup Oro (2007)"],
        ncaa_accolades=[],
        career_ppg=27.1,
        career_rpg=7.5,
        career_apg=7.4,
        peak_per=31.7,
        peak_bpm=13.0,
        tactical_summary="Máximo anotador histórico de la NBA (40.000+ pts). 20 veces All-NBA, 4 anillos en 3 franquicias distintas y 3 oros olímpicos. Certeza absoluta 100% en primera votación.",
        tactical_summary_en="All-time leading scorer in NBA history (40,000+ pts). 20x All-NBA, 4 championships across 3 franchises, and 3 Olympic Golds. 100% first-ballot lock.",
    ),
    HOFPlayerItem(
        player_id=201939,
        player_name="Stephen Curry",
        status="active_lock",
        induction_year=None,
        hof_probability=1.0,
        primary_archetype="Primary Ball Handler & Creator",
        career_span="2009 - Presente",
        team_abbreviation="GSW",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png",
        nba_championships=4,
        mvp_count=2,
        finals_mvp_count=1,
        all_star_count=10,
        all_nba_count=10,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico París (2024)"],
        fiba_accolades=["🏆 2x Campeón Mundial FIBA (2010, 2014)"],
        ncaa_accolades=["🌟 Elite Eight NCAA (Davidson 2008)"],
        career_ppg=24.8,
        career_rpg=4.7,
        career_apg=6.4,
        peak_per=31.5,
        peak_bpm=11.9,
        tactical_summary="El mejor tirador en la historia del básquetbol. Transformó la táctica y geometría de este deporte en el siglo XXI. Único MVP unánime de la historia de la NBA.",
        tactical_summary_en="The greatest shooter in basketball history. Fundamentally transformed modern basketball geometry and analytics. Sole unanimous MVP in NBA history.",
    ),
    HOFPlayerItem(
        player_id=201142,
        player_name="Kevin Durant",
        status="active_lock",
        induction_year=None,
        hof_probability=1.0,
        primary_archetype="Versatile Wing / Playmaking Forward",
        career_span="2007 - Presente",
        team_abbreviation="PHX",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
        nba_championships=2,
        mvp_count=1,
        finals_mvp_count=2,
        all_star_count=14,
        all_nba_count=11,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico (2012)", "🥇 Oro Olímpico (2016)", "🥇 Oro Olímpico (2020)", "🥇 Oro Olímpico (2024)"],
        fiba_accolades=["🏆 Campeón Mundial FIBA & MVP (2010)"],
        ncaa_accolades=["🌟 Naismith College Player of the Year (2007 Texas)"],
        career_ppg=27.3,
        career_rpg=7.0,
        career_apg=4.4,
        peak_per=29.8,
        peak_bpm=8.8,
        tactical_summary="Uno de los anotadores puros más letales de la historia. Máximo anotador olímpico de EE.UU. con 4 medallas de oro consecutivas, 4 títulos de anotación y 2 MVP de Finales.",
        tactical_summary_en="One of the most lethal pure scorers in sports history. USA Basketball's all-time Olympic leading scorer with 4 consecutive Gold medals, 4 scoring titles, and 2 Finals MVPs.",
    ),
    HOFPlayerItem(
        player_id=203999,
        player_name="Nikola Jokić",
        status="active_lock",
        induction_year=None,
        hof_probability=0.998,
        primary_archetype="Unicorn & Hub Center",
        career_span="2015 - Presente",
        team_abbreviation="DEN",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/203999.png",
        nba_championships=1,
        mvp_count=3,
        finals_mvp_count=1,
        all_star_count=6,
        all_nba_count=6,
        dpoy_count=0,
        olympic_medals=["🥈 Plata Olímpica (2016 Serbia)", "🥉 Bronce Olímpico (2024 Serbia)"],
        fiba_accolades=["🌟 MVP Liga ABA (2015)"],
        ncaa_accolades=[],
        career_ppg=20.9,
        career_rpg=10.7,
        career_apg=6.9,
        peak_per=32.8,
        peak_bpm=13.7,
        tactical_summary="3 veces MVP de la NBA y campeón 2023. Poseedor de las temporadas analíticamente más eficientes de la historia (PER 32.8, BPM 13.7) y medallas olímpicas con Serbia.",
        tactical_summary_en="3x NBA MVP and 2023 Champion. Boasts the most analytically efficient seasons in basketball history (PER 32.8, BPM 13.7) along with two Olympic medals for Serbia.",
    ),
    HOFPlayerItem(
        player_id=203507,
        player_name="Giannis Antetokounmpo",
        status="active_lock",
        induction_year=None,
        hof_probability=0.996,
        primary_archetype="Versatile Wing / Playmaking Forward",
        career_span="2013 - Presente",
        team_abbreviation="MIL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png",
        nba_championships=1,
        mvp_count=2,
        finals_mvp_count=1,
        all_star_count=8,
        all_nba_count=8,
        dpoy_count=1,
        olympic_medals=[],
        fiba_accolades=["🌟 Quinteto Ideal EuroBasket (2022 Grecia)"],
        ncaa_accolades=[],
        career_ppg=23.4,
        career_rpg=9.8,
        career_apg=4.9,
        peak_per=31.9,
        peak_bpm=11.0,
        tactical_summary="'The Greek Freak', uno de los únicos 3 jugadores en ganar MVP, Finals MVP y DPOY (junto a Jordan y Olajuwon). Actuación de 50 puntos para coronarse campeón en 2021.",
        tactical_summary_en="'The Greek Freak', one of only three players in NBA history to win MVP, Finals MVP, and DPOY (joining Jordan and Olajuwon). Iconic 50-point Game 6 title clincher.",
    ),
    HOFPlayerItem(
        player_id=203076,
        player_name="Anthony Davis",
        status="active_lock",
        induction_year=None,
        hof_probability=0.985,
        primary_archetype="Rim Protector & Rolling Big",
        career_span="2012 - Presente",
        team_abbreviation="LAL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png",
        nba_championships=1,
        mvp_count=0,
        finals_mvp_count=0,
        all_star_count=9,
        all_nba_count=5,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico (2012)", "🥇 Oro Olímpico (2024)"],
        fiba_accolades=["🏆 Campeón Mundial FIBA (2014)"],
        ncaa_accolades=["🏆 Campeón Nacional NCAA & MOP (2012 Kentucky)", "🌟 Naismith College Player of the Year"],
        career_ppg=24.1,
        career_rpg=10.6,
        career_apg=2.5,
        peak_per=30.3,
        peak_bpm=8.5,
        tactical_summary="Uno de los 7 jugadores en la historia en ganar el 'Grand Slam del Básquetbol': NCAA Champion, Olympic Gold, FIBA World Champion y NBA Champion.",
        tactical_summary_en="One of only 7 players in history to complete basketball's 'Grand Slam': NCAA Champion, Olympic Gold, FIBA World Champion, and NBA Champion.",
    ),
    HOFPlayerItem(
        player_id=1629029,
        player_name="Luka Dončić",
        status="active_high",
        induction_year=None,
        hof_probability=0.895,
        primary_archetype="Primary Ball Handler & Creator",
        career_span="2018 - Presente",
        team_abbreviation="DAL",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png",
        nba_championships=0,
        mvp_count=0,
        finals_mvp_count=0,
        all_star_count=5,
        all_nba_count=5,
        dpoy_count=0,
        olympic_medals=[],
        fiba_accolades=["🏆 Campeón EuroBasket (2017 Eslovenia)", "🏆 Campeón EuroLeague & MVP (2018 Real Madrid)"],
        ncaa_accolades=[],
        career_ppg=28.7,
        career_rpg=8.7,
        career_apg=8.3,
        peak_per=31.2,
        peak_bpm=10.2,
        tactical_summary="5 selecciones All-NBA First Team en sus primeras 6 temporadas (hazaña solo igualada por Larry Bird y Tim Duncan). Currículum europeo histórico antes de los 19 años.",
        tactical_summary_en="5x All-NBA First Team in his first six seasons (equaling Larry Bird and Tim Duncan). Historic European championship and MVP resume before age 19.",
    ),
    HOFPlayerItem(
        player_id=1628369,
        player_name="Jayson Tatum",
        status="active_high",
        induction_year=None,
        hof_probability=0.820,
        primary_archetype="Versatile Wing / Playmaking Forward",
        career_span="2017 - Presente",
        team_abbreviation="BOS",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
        nba_championships=1,
        mvp_count=0,
        finals_mvp_count=0,
        all_star_count=5,
        all_nba_count=4,
        dpoy_count=0,
        olympic_medals=["🥇 Oro Olímpico Tokio (2020)", "🥇 Oro Olímpico París (2024)"],
        fiba_accolades=[],
        ncaa_accolades=["🌟 ACC All-Freshman (Duke)"],
        career_ppg=23.1,
        career_rpg=7.2,
        career_apg=3.5,
        peak_per=23.7,
        peak_bpm=5.5,
        tactical_summary="Líder del campeonato #18 de Boston Celtics (2024), bicampeón olímpico y 3 selecciones consecutivas All-NBA 1st Team a los 26 años.",
        tactical_summary_en="Leader of the Boston Celtics' 18th NBA Championship (2024), 2x Olympic Gold medalist, and 3x consecutive All-NBA 1st Team at age 26.",
    ),
    HOFPlayerItem(
        player_id=1641705,
        player_name="Victor Wembanyama",
        status="active_rising",
        induction_year=None,
        hof_probability=0.680,
        primary_archetype="Unicorn & Hub Center",
        career_span="2023 - Presente",
        team_abbreviation="SAS",
        headshot_url="https://cdn.nba.com/headshots/nba/latest/1040x760/1641705.png",
        nba_championships=0,
        mvp_count=0,
        finals_mvp_count=0,
        all_star_count=0,
        all_nba_count=0,
        dpoy_count=0,
        olympic_medals=["🥈 Plata Olímpica París (2024 Francia)"],
        fiba_accolades=["🌟 MVP Liga Pro A de Francia (2023)"],
        ncaa_accolades=[],
        career_ppg=21.4,
        career_rpg=10.6,
        career_apg=3.9,
        peak_per=23.1,
        peak_bpm=5.2,
        tactical_summary="El prospecto más revolucionario en la historia de la liga. Líder de tapones de la NBA como novato (3.6 BPG), All-Defensive First Team y Plata Olímpica a los 20 años.",
        tactical_summary_en="The most revolutionary prospect in league history. NBA blocks leader as a rookie (3.6 BPG), All-Defensive First Team, and Olympic Silver medal at age 20.",
    ),
]


@router.get("/hall-of-fame", response_model=List[HOFPlayerItem])
def get_hall_of_fame_list(
    status_filter: Optional[str] = Query(default=None, description="inducted, active, or all")
):
    if not status_filter or status_filter == "all":
        return HOF_DATABASE
    if status_filter == "inducted":
        return [p for p in HOF_DATABASE if p.status == "inducted"]
    if status_filter == "active":
        return [p for p in HOF_DATABASE if p.status.startswith("active")]
    return HOF_DATABASE
