"""add_player_matchup_stats

Revision ID: 4125a71b06bf
Revises: ad04e02dc85c
Create Date: 2026-09-05 00:30:05.531214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4125a71b06bf'
down_revision: Union[str, Sequence[str], None] = 'ad04e02dc85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('annual_salary', sa.Float(), nullable=False),
    sa.Column('cap_hit_pct', sa.Float(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('years_remaining', sa.Integer(), nullable=False),
    sa.Column('free_agency_year', sa.Integer(), nullable=False),
    sa.Column('is_guaranteed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_contract_player_id'), 'player_contract', ['player_id'], unique=False)
    op.create_table('player_matchup_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('off_player_id', sa.Integer(), nullable=False),
    sa.Column('def_player_id', sa.Integer(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=False),
    sa.Column('matchup_min', sa.Float(), nullable=False),
    sa.Column('partial_poss', sa.Float(), nullable=False),
    sa.Column('player_pts', sa.Float(), nullable=False),
    sa.Column('team_pts', sa.Float(), nullable=False),
    sa.Column('matchup_ast', sa.Float(), nullable=False),
    sa.Column('matchup_tov', sa.Float(), nullable=False),
    sa.Column('matchup_blk', sa.Float(), nullable=False),
    sa.Column('matchup_fgm', sa.Float(), nullable=False),
    sa.Column('matchup_fga', sa.Float(), nullable=False),
    sa.Column('matchup_fg_pct', sa.Float(), nullable=False),
    sa.Column('matchup_fg3m', sa.Float(), nullable=False),
    sa.Column('matchup_fg3a', sa.Float(), nullable=False),
    sa.Column('matchup_fg3_pct', sa.Float(), nullable=False),
    sa.Column('help_blk', sa.Float(), nullable=False),
    sa.Column('help_fgm', sa.Float(), nullable=False),
    sa.Column('help_fga', sa.Float(), nullable=False),
    sa.Column('help_fg_perc', sa.Float(), nullable=False),
    sa.Column('matchup_ftm', sa.Float(), nullable=False),
    sa.Column('matchup_fta', sa.Float(), nullable=False),
    sa.Column('sfl', sa.Float(), nullable=False),
    sa.Column('matchup_time_sec', sa.Float(), nullable=False),
    sa.Column('ts_pct', sa.Float(), nullable=False),
    sa.Column('pts_per_75', sa.Float(), nullable=False),
    sa.Column('ast_per_75', sa.Float(), nullable=False),
    sa.Column('tov_per_75', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['def_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['off_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'off_player_id', 'def_player_id', name='uq_matchup_season_off_def')
    )
    op.create_index('ix_matchup_def_poss', 'player_matchup_stats', ['def_player_id', 'partial_poss'], unique=False)
    op.create_index('ix_matchup_off_poss', 'player_matchup_stats', ['off_player_id', 'partial_poss'], unique=False)
    op.create_index('ix_matchup_season_off', 'player_matchup_stats', ['season_id', 'off_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matchup_season_off', table_name='player_matchup_stats')
    op.drop_index('ix_matchup_off_poss', table_name='player_matchup_stats')
    op.drop_index('ix_matchup_def_poss', table_name='player_matchup_stats')
    op.drop_table('player_matchup_stats')
    op.drop_index(op.f('ix_player_contract_player_id'), table_name='player_contract')
    op.drop_table('player_contract')
    # ### end Alembic commands ###
