"""add_quant_paper_trading

Hand-written (not autogenerated): PostgreSQL 15 only. Uses native enums,
GENERATED ALWAYS columns, NULLS NOT DISTINCT unique constraints, a BRIN index
and two reporting views. Keep in sync with "Phase 4: Quant Paper Trading" in
app/models.py.

Revision ID: 9c3e5a7d1f42
Revises: 4125a71b06bf
Create Date: 2026-10-06 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9c3e5a7d1f42'
down_revision: Union[str, Sequence[str], None] = '4125a71b06bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


MARKET_TYPES = (
    'h2h', 'spreads', 'totals',
    'player_points', 'player_rebounds', 'player_assists', 'player_pra',
)
BET_SIDES = ('home', 'away', 'over', 'under')
BET_STATUSES = ('pending', 'won', 'lost', 'push', 'void')
STAKING_STRATEGIES = ('flat', 'kelly_fractional')

ENUMS = (
    ('market_type', MARKET_TYPES),
    ('bet_side', BET_SIDES),
    ('bet_status', BET_STATUSES),
    ('staking_strategy', STAKING_STRATEGIES),
)


def _enum(name: str, values: Sequence[str]) -> postgresql.ENUM:
    # create_type=False: the types are created exactly once, explicitly, in
    # upgrade() below, so several columns can share one type.
    return postgresql.ENUM(*values, name=name, create_type=False)


def upgrade() -> None:
    for name, values in ENUMS:
        labels = ", ".join(f"'{v}'" for v in values)
        op.execute(f"CREATE TYPE {name} AS ENUM ({labels})")

    op.create_table('sportsbook',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('is_sharp', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_sportsbook_key')
    )

    op.create_table('game',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nba_game_id', sa.Text(), nullable=True),
    sa.Column('provider_event_id', sa.Text(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_game_id', name='uq_game_nba_game_id'),
    sa.UniqueConstraint('provider_event_id', name='uq_game_provider_event_id'),
    sa.CheckConstraint('home_team_id <> away_team_id', name='ck_game_distinct_teams'),
    sa.CheckConstraint("status IN ('scheduled', 'live', 'final', 'postponed')", name='ck_game_status')
    )
    op.create_index('ix_game_commence_time', 'game', ['commence_time'], unique=False)

    op.create_table('odds_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('sportsbook_id', sa.SmallInteger(), nullable=False),
    sa.Column('market', _enum('market_type', MARKET_TYPES), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('side', _enum('bet_side', BET_SIDES), nullable=False),
    sa.Column('line', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('price_american', sa.Integer(), nullable=False),
    sa.Column('price_decimal', sa.Numeric(precision=8, scale=4), sa.Computed(
        'CASE WHEN price_american > 0 THEN 1 + price_american / 100.0 '
        'ELSE 1 + 100.0 / ABS(price_american) END', persisted=True), nullable=True),
    sa.Column('book_last_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbook.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('price_american <= -100 OR price_american >= 100', name='ck_odds_price_american'),
    # player_id and line are NULL for game markets, so NULLs must compare equal.
    sa.UniqueConstraint('game_id', 'sportsbook_id', 'market', 'player_id', 'side', 'line', 'book_last_update',
                        name='uq_odds_history_quote', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_odds_history_lookup', 'odds_history',
                    ['game_id', 'market', 'player_id', 'side', 'sportsbook_id', sa.text('captured_at DESC')],
                    unique=False)
    op.create_index('ix_odds_history_captured_brin', 'odds_history', ['captured_at'],
                    unique=False, postgresql_using='brin')

    op.create_table('model_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('brier_oos', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version_name_version')
    )

    op.create_table('model_prediction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('market', _enum('market_type', MARKET_TYPES), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('side', _enum('bet_side', BET_SIDES), nullable=False),
    sa.Column('line', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('model_prob', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('fair_decimal', sa.Numeric(precision=8, scale=4), sa.Computed('1 / model_prob', persisted=True), nullable=True),
    sa.Column('projection', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('model_prob > 0 AND model_prob < 1', name='ck_prediction_prob_range'),
    sa.UniqueConstraint('model_version_id', 'game_id', 'market', 'player_id', 'side', 'line',
                        name='uq_model_prediction_target', postgresql_nulls_not_distinct=True)
    )

    op.create_table('simulated_bet',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('odds_taken_id', sa.BigInteger(), nullable=False),
    sa.Column('price_taken', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('line_taken', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('fair_prob_at_bet', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('ev_per_unit', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('strategy', _enum('staking_strategy', STAKING_STRATEGIES), nullable=False),
    sa.Column('kelly_multiplier', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('stake_units', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('bankroll_before', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('closing_odds_id', sa.BigInteger(), nullable=True),
    sa.Column('closing_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('closing_line', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('clv_pct', sa.Numeric(precision=7, scale=5), sa.Computed('price_taken / closing_price - 1', persisted=True), nullable=True),
    sa.Column('status', _enum('bet_status', BET_STATUSES), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('profit_units', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['model_prediction.id'], ),
    sa.ForeignKeyConstraint(['odds_taken_id'], ['odds_history.id'], ),
    sa.ForeignKeyConstraint(['closing_odds_id'], ['odds_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('stake_units > 0', name='ck_simulated_bet_stake_positive'),
    sa.CheckConstraint('closing_price IS NULL OR closing_price > 0', name='ck_simulated_bet_closing_price'),
    sa.CheckConstraint("status = 'pending' OR settled_at IS NOT NULL", name='ck_simulated_bet_settled_at')
    )
    op.create_index('ix_simulated_bet_pending', 'simulated_bet', ['status'], unique=False,
                    postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_simulated_bet_strategy_placed', 'simulated_bet', ['strategy', 'placed_at'], unique=False)

    # Latest quote per (game, book, market, player, side, line) at or before tip-off.
    op.execute("""
        CREATE VIEW v_closing_odds AS
        SELECT DISTINCT ON (o.game_id, o.sportsbook_id, o.market, o.player_id, o.side, o.line) o.*
        FROM odds_history o JOIN game g ON g.id = o.game_id
        WHERE o.captured_at <= g.commence_time
        ORDER BY o.game_id, o.sportsbook_id, o.market, o.player_id, o.side, o.line, o.captured_at DESC
    """)

    op.execute("""
        CREATE VIEW v_paper_performance AS
        SELECT strategy,
               COUNT(*) FILTER (WHERE status IN ('won','lost','push')) AS settled,
               AVG((status = 'won')::int) FILTER (WHERE status IN ('won','lost')) AS win_rate,
               SUM(profit_units) AS pnl_units,
               SUM(profit_units) / NULLIF(SUM(stake_units) FILTER (WHERE status IN ('won','lost','push')), 0) AS roi,
               AVG(clv_pct) AS avg_clv,
               AVG((clv_pct > 0)::int) AS beat_close_rate
        FROM simulated_bet GROUP BY strategy
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_paper_performance")
    op.execute("DROP VIEW IF EXISTS v_closing_odds")

    op.drop_index('ix_simulated_bet_strategy_placed', table_name='simulated_bet')
    op.drop_index('ix_simulated_bet_pending', table_name='simulated_bet',
                  postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('simulated_bet')
    op.drop_table('model_prediction')
    op.drop_table('model_version')
    op.drop_index('ix_odds_history_captured_brin', table_name='odds_history', postgresql_using='brin')
    op.drop_index('ix_odds_history_lookup', table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index('ix_game_commence_time', table_name='game')
    op.drop_table('game')
    op.drop_table('sportsbook')

    for name, _values in reversed(ENUMS):
        op.execute(f"DROP TYPE IF EXISTS {name}")
